version: '1.0'

networks:
  wp-nwk: {}

volumes:
  wp-db-data:
  wp-static:

services:
  wp-mysql: 
    image: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=paiement-service
      - MYSQL_PASSWORD=paiement-service
      - MYSQL_DATABASE=paiement
    networks:
      - wp-nwk
    volumes:
      - wp-db-data:/var/lib/mysql
    ports:
      - "10000:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 3s
      retries: 10
    
  paiementservice:
    image: ${DOCKER_REGISTRY-}paiementservice
    networks:
      - wp-nwk
    ports:
      - "44383:443"
    depends_on:
      wp-mysql:
        condition: service_healthy
